export const ORDER_DATA = {
  orderId: -1,
  email: "kk20241029-02@yopmail.com",
  shippingAddress: {
    id: 23489948,
    description: "Last, Test, Monterey",
    first: "Test",
    last: "Last",
    address1: "1 lower ragsdale dr",
    address2: "",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    city: "Monterey",
    state: "CA",
    country: "United States",
    isoalpha3Code: "USA",
    region: "",
    zip: "93940",
    phone: "",
    isPoBox: false,
  },
  billingAddress: {
    id: 23489948,
    description: "Last, Test, Monterey",
    first: "Test",
    last: "Last",
    address1: "1 lower ragsdale dr",
    address2: "",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    city: "Monterey",
    state: "CA",
    country: "United States",
    isoalpha3Code: "USA",
    region: "",
    zip: "93940",
    phone: "",
    isPoBox: false,
  },
  paymentMethod: {
    id: 99297490,
    number: "411111******1111",
    cvv: "999",
    type: "Visa",
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    token: "2df0e8b5-e8fb-11df-b64c-005056842e7d",
    accountName: "test card",
    mask: "411111******1111",
    expMonth: 1,
    expYear: 2027,
    typeID: 9,
  },
  id: "cart_1182228987_W_USA_USA_ENG",
  stores: {
    "72094-IN_STOCK": {
      totals: {
        price: 149.9,
        cashBack: 3.0,
        bv: 90.0,
        ibv: 0.0,
      },
      items: [
        {
          prodId: "603139941",
          image: {
            url: "https://img.shop.com/Image/210000/214100/214196/products/36127105Single_Bottle__90_Servings_.jpg?size=100x100",
          },
          caption: "Isotonix OPC-3&reg;",
          catalogSku: "2217",
          catalogName: "Market America",
          specialFormula: "0",
          quantity: 2,
          option: [
            {
              optionStringValue: "Single Bottle (90 Servings)",
            },
          ],
          totals: {
            price: 149.9,
            cashBack: 3.0,
            bv: 90.0,
            ibv: 0.0,
          },
        },
      ],
      shippingMethod: "Standard",
      deliveryMessage: "",
      shippingSelections: [
        {
          id: 1,
          method: "Standard",
          total: 0.0,
          estShipDate: "10-7 business days",
        },
      ],
      shipping: {
        id: 1,
        method: "Standard",
        total: 0.0,
        estShipDate: "3-2 business days",
      },
    },
    "108567": {
      totals: {
        price: 199.96,
        cashBack: 0.0,
        bv: 0.0,
        ibv: 15.84,
      },
      items: [
        {
          prodId: "1825001247",
          image: {
            url: "https://img.shop.com/Image/250000/259100/259190/products/1855205799.jpg?size=100x100",
          },
          caption:
            "Sonic the Hedgehog Red Running Shoes Plush Cosplay Slippers | One Size",
          catalogSku: "GEE-74771-C",
          catalogName: "Toynk",
          specialFormula: "0",
          quantity: 3,
          option: [],
          totals: {
            price: 131.97,
            cashBack: 0.0,
            bv: 0.0,
            ibv: 15.84,
          },
        },
      ],
      shippingMethod: "Next Day",
      deliveryMessage: "",
      shippingSelections: [
        {
          id: 1,
          method: "Standard",
          total: 0.0,
          estShipDate: "10-7 business days",
        },
        {
          id: 3,
          method: "Next Day",
          total: 67.99,
          estShipDate: "3-2 business days",
        },
        {
          id: 4,
          method: "2 Day",
          total: 41.99,
          estShipDate: "4-3 business days",
        },
        {
          id: 5,
          method: "Express",
          total: 19.99,
          estShipDate: "6-4 business days",
        },
      ],
      shipping: {
        id: 3,
        method: "Next Day",
        total: 67.99,
        estShipDate: "3-2 business days",
      },
    },
  },
  userOptions: {
    applyCashback: false,
    applyEWallet: false,
    isOfAge: false,
    trackingId: "",
    deliveryDate: "",
    deliveryTime: 1234567890,
    signatureRequired: false,
    oosConsolidate: false,
    userSessionId: "",
    tempOrderID: "null",
  },
  paymentMethods: [
    {
      typeID: 56,
      type: "Sezzle",
      imageTag: "",
      supportedForAutoship: false,
      visible: false,
    },
    {
      typeID: 31,
      type: "PayPal",
      imageTag: "^imageserver/local/images/cc/paypal.svg",
      visible: false,
    },
    {
      typeID: 49,
      type: "Paypal Credit",
      imageTag: "^imageserver/local/images/cc/ppc-acceptance-small.svg",
      visible: false,
    },
    {
      typeID: 60,
      type: "C2P",
      imageTag: "^imageserver/local/images/cc/c2p.svg",
      supportedForAutoship: true,
      visible: false,
    },
    {
      typeID: 9,
      type: "Visa",
      imageTag: "^imageserver/local/images/cc/visa.svg",
      supportedForAutoship: true,
      visible: true,
    },
    {
      typeID: 1,
      type: "American Express",
      imageTag: "^imageserver/local/images/cc/amex.svg",
      supportedForAutoship: true,
      visible: true,
    },
    {
      typeID: 5,
      type: "Discover",
      imageTag: "^imageserver/local/images/cc/discover.svg",
      supportedForAutoship: true,
      visible: true,
    },
  ],
  totals: {
    price: 57.0,
    shipping: 0.0,
    cashback: 0.0,
    bv: 90.0,
    ibv: 0.0,
    tax: 0.0,
  },
};
