export const ORDER_DATA = {
  orderId: -1,
  email: "dev_test_new0512@yopmail.com",
  shippingAddress: {
    id: 22640290,
    description: "test, dev, monterey",
    first: "dev",
    last: "test",
    address1: "123 test rd",
    address2: "",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    city: "monterey",
    state: "CA",
    country: "United States",
    isoalpha3Code: "USA",
    region: "",
    zip: "93940",
    phone: "1112223333",
    isPoBox: false,
  },
  billingAddress: {
    id: 22640290,
    description: "test, dev, monterey",
    first: "dev",
    last: "test",
    address1: "123 test rd",
    address2: "",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    city: "monterey",
    state: "CA",
    country: "United States",
    isoalpha3Code: "USA",
    region: "",
    zip: "93940",
    phone: "1112223333",
    isPoBox: false,
  },
  paymentMethod: {
    id: 99297419,
    number: "411111******1111",
    cvv: "123",
    type: "Visa",
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    typeID: 9,
  },
  id: "cart_2282210204_W_USA_USA_ENG",
  stores: {
    "108567": {
      totals: {
        price: 89.97,
        cashBack: 5.4,
        bv: 0.0,
        ibv: 6.0,
        shipping: 0.0,
        tax: 0.0,
        priceStr: "$89.97",
        shippingStr: "$0.00",
        taxStr: "$0.00",
        cashBackStr: "$5.40",
      },
      items: [
        {
          prodId: "1502492236",
          image: {
            url: "https://img.shop.com/Image/250000/259100/259190/products/1533507525.jpg?size=100x100",
          },
          caption: 'Minecraft 7" Plush: Enderman',
          catalogSku: "JZW-16523-C",
          productType: "ONE",
          storeMaVendorId: "1887",
          prodContainerId: 1533507525,
          catalogName: "Toynk",
          specialFormula: "0",
          quantity: 2,
          option: [],
          product_hash:
            "0cd127c40c32d52d49f91fe0aaa1d8ea97619623a25d12fa2c0c70b50db1487a",
          totals: {
            price: 59.98,
            cashBack: 3.6,
            bv: 0.0,
            ibv: 4.8,
          },
        },
        {
          prodId: "1502492236",
          image: {
            url: "https://img.shop.com/Image/250000/259100/259190/products/1533507525.jpg?size=100x100",
          },
          caption: 'Minecraft 7" Plush: Enderman',
          catalogSku: "JZW-16523-C",
          productType: "ONE",
          storeMaVendorId: "1887",
          prodContainerId: 1533507525,
          catalogName: "Toynk",
          specialFormula: "0",
          quantity: 1,
          product_hash:
            "727d577fe4146736a9d8d99086370b73a7cf140204c55c1de27ac5a828809d76",
          totals: {
            price: 29.99,
            cashBack: 1.8,
            bv: 0.0,
            ibv: 1.2,
          },
        },
      ],
      shippingMethod: "Standard",
      deliveryMessage: "",
      shippingSelections: [
        {
          id: 1,
          method: "Standard",
          total: 0.0,
          estShipDate: "Jan. 1 - Jan. 6",
        },
        {
          id: 3,
          method: "Next Day",
          total: 55.99,
          estShipDate: "Dec. 25 - Dec. 26",
        },
        {
          id: 4,
          method: "2 Day",
          total: 35.99,
          estShipDate: "Dec. 26 - Dec. 27",
        },
        {
          id: 5,
          method: "Express",
          total: 18.99,
          estShipDate: "Dec. 27 - Dec. 31",
        },
      ],
      shipping: {
        id: 1,
        method: "Standard",
        total: 0.0,
        estShipDate: "Jan. 1 - Jan. 6",
      },
    },
    "72094-IN_STOCK": {
      totals: {
        price: 266.85,
        cashBack: 5.34,
        bv: 158.0,
        ibv: 0.0,
        shipping: 0.0,
        tax: 0.0,
        priceStr: "$266.85",
        shippingStr: "$0.00",
        taxStr: "$0.00",
        cashBackStr: "$5.34",
      },
      items: [
        {
          prodId: "1911928805",
          image: {
            url: "https://img.shop.com/Image/240000/248600/248698/products/1942133542.jpg?size=100x100",
          },
          caption:
            "Lumi&egrave;re de Vie&reg; Hydrate 3.0 (Hyaluronic Acid Serum)",
          catalogSku: "5821606",
          productType: "MA",
          storeMaVendorId: "00USA",
          prodContainerId: 1942133542,
          merchantSku: "12253",
          catalogName: "Market America",
          specialFormula: "0",
          quantity: 1,
          option: [
            {
              optionStringValue: "Single Bottle (1.0 fl oz/30 ml)",
            },
          ],
          product_hash:
            "e9767e00d73dfb31513c5e479b1092b6b1a492b96e4cbd50d113121f94da30e6",
          totals: {
            price: 42.0,
            cashBack: 0.84,
            bv: 23.0,
            ibv: 0.0,
          },
        },
        {
          prodId: "603139941",
          image: {
            url: "https://img.shop.com/Image/210000/214100/214196/products/36127105Single_Bottle__90_Servings_.jpg?size=100x100",
          },
          caption: "Isotonix OPC-3&reg;",
          catalogSku: "2217",
          productType: "MA",
          storeMaVendorId: "00USA",
          prodContainerId: 561800349,
          merchantSku: "13009",
          catalogName: "Market America",
          specialFormula: "0",
          quantity: 3,
          option: [
            {
              optionStringValue: "Single Bottle (90 Servings)",
              name: "",
            },
          ],
          product_hash:
            "803c532967abf1e533aab35014818b850f4b7474c3b3d07b32449867911491e3",
          totals: {
            price: 224.85,
            cashBack: 4.5,
            bv: 135.0,
            ibv: 0.0,
          },
        },
      ],
      shippingMethod: "UPS Ground (1 to 6 days)",
      deliveryMessage: "12-27-2024",
      shippingSelections: [
        {
          id: 42,
          method: "Standard Shipping",
          total: 0.0,
          estShipDate: "12-30-2024",
        },
        {
          id: 46,
          method: "3 Day Expedited Shipping (excludes Saturdays and Sundays)",
          total: 15.74,
          estShipDate: "12-27-2024",
        },
        {
          id: 45,
          method: "2 Day Expedited Shipping (excludes Saturdays and Sundays)",
          total: 16.34,
          estShipDate: "12-27-2024",
        },
        {
          id: 44,
          method: "Overnight (excludes Saturdays and Sundays)",
          total: 28.99,
          estShipDate: "12-26-2024",
        },
      ],
    },
  },
  userOptions: {
    applyCashback: false,
    applyEWallet: false,
    isOfAge: false,
    trackingID: "",
    deliveryDate: "",
    signatureRequired: false,
    oosConsolidate: 3,
    userSessionId: "",
    coupons: [],
    tempOrderID: "491090",
  },
  paymentMethods: [
    {
      typeID: 56,
      type: "Sezzle",
      imageTag: "",
      supportedForAutoship: false,
      visible: false,
    },
    {
      typeID: 31,
      type: "PayPal",
      imageTag: "^imageserver/local/images/cc/paypal.svg",
      visible: false,
    },
    {
      typeID: 49,
      type: "Paypal Credit",
      imageTag: "^imageserver/local/images/cc/ppc-acceptance-small.svg",
      visible: false,
    },
    {
      typeID: 60,
      type: "C2P",
      imageTag: "^imageserver/local/images/cc/c2p.svg",
      supportedForAutoship: true,
      visible: false,
    },
    {
      typeID: 9,
      type: "Visa",
      imageTag: "^imageserver/local/images/cc/visa.svg",
      supportedForAutoship: true,
      visible: true,
    },
    {
      typeID: 1,
      type: "American Express",
      imageTag: "^imageserver/local/images/cc/amex.svg",
      supportedForAutoship: true,
      visible: true,
    },
    {
      typeID: 5,
      type: "Discover",
      imageTag: "^imageserver/local/images/cc/discover.svg",
      supportedForAutoship: true,
      visible: true,
    },
  ],
  totals: {
    cashBack: 8.94,
    bv: 158.0,
    ibv: 3.6,
    cashBackApplied: 0.0,
    walletApplied: 0.0,
    price: 356.82,
    shipping: 0.0,
    tax: 0.0,
    priceStr: "$356.82",
    cashBackStr: "$10.74",
    taxStr: "$0.00",
    shippingStr: "$0.00",
    cashBackAppliedStr: "$0.00",
    walletAppliedStr: "$0.00",
  },
};

export const ADDRESS_BOOK = [
  {
    isShip: 0,
    isBill: 1,
    isPrimary: 0,
    hasAddress: 1,
    id: 22621330,
    description: "update2, update1, Monterey",
    prefix: "",
    first: "update1",
    mi: "",
    last: "update2",
    company: "",
    address1: "po box 421212",
    address2: "",
    city: "Monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "1112223333",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    hashCode: "",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/22621330?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 1,
    hasAddress: 1,
    id: 22640290,
    description: "test, dev, monterey",
    prefix: "",
    first: "dev",
    mi: "",
    last: "test",
    company: "",
    address1: "123 test rd",
    address2: "",
    city: "monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "1112223333",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/22640290?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23493568,
    description: "2312, Test 17 Dec, NY",
    prefix: "",
    first: "Test 17 Dec",
    mi: "",
    last: "2312",
    company: "",
    address1: "Latest Street 1",
    address2: "",
    city: "NY",
    state: "NY",
    region: "",
    zip: "10001",
    country: "United States",
    phone: "1111110000",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23493568?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 22624172,
    description: "update2, update1, Monterey",
    prefix: "",
    first: "update1",
    mi: "",
    last: "update2",
    company: "",
    address1: "po box 456",
    address2: "",
    city: "Monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "1112223333",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    hashCode: "",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/22624172?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 22623877,
    description: "special characters 测试, test...",
    prefix: "",
    first: "test",
    mi: "",
    last: "special characters 测试",
    company: "",
    address1: "testing address spec char 测试",
    address2: "",
    city: "monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "1112223333",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/22623877?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23172392,
    description: "test, test, monterey",
    prefix: "",
    first: "test",
    mi: "",
    last: "test",
    company: "",
    address1: "21 lower ragsdale dr",
    address2: "",
    city: "monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "8314562345",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: true,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23172392?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23428420,
    description: "test, po, monterey",
    prefix: "",
    first: "po",
    mi: "",
    last: "test",
    company: "",
    address1: "123 test MC rd",
    address2: "",
    city: "monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "1112222333",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23428420?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23240818,
    description: "test, test, monterey",
    prefix: "",
    first: "test",
    mi: "",
    last: "test",
    company: "",
    address1: "postal box 764",
    address2: "testing AI-97101",
    city: "monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "1112223333",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: true,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23240818?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23221325,
    description: "test, test, monterey",
    prefix: "",
    first: "test",
    mi: "",
    last: "test",
    company: "",
    address1: "21 lower ragsdale dr",
    address2: "",
    city: "monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "8314562345",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    hashCode: "",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23221325?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 1,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23207860,
    description: "test, express, monterey",
    prefix: "",
    first: "express",
    mi: "",
    last: "test",
    company: "",
    address1: "562 express add test",
    address2: "",
    city: "monterey",
    state: "CA",
    region: "",
    zip: "93940",
    country: "United States",
    phone: "1112223333",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    hashCode: "",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23207860?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23493569,
    description: "Dec, Test 18, NY",
    prefix: "",
    first: "Test 18",
    mi: "",
    last: "Dec",
    company: "",
    address1: "Street 1",
    address2: "",
    city: "NY",
    state: "NY",
    region: "",
    zip: "10001",
    country: "United States",
    phone: "1000011110",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23493569?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
  {
    isShip: 0,
    isBill: 0,
    isPrimary: 0,
    hasAddress: 1,
    id: 23183828,
    description: "carolina, test, Greensboro",
    prefix: "",
    first: "test",
    mi: "",
    last: "carolina",
    company: "",
    address1: "1150 Pleasant Ridge Rd",
    address2: "",
    city: "Greensboro",
    state: "NC",
    region: "",
    zip: "27409",
    country: "United States",
    phone: "8885556666",
    address3: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    zone: 0,
    isPoBox: false,
    isoalpha3Code: "USA",
    shopperAccountDisabled: 0,
    links: {
      rel: "update",
      href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/AddressBook/23183828?siteId=260",
      type: "application/json; charset=UTF-8",
    },
  },
];

export const WALLET_DATA = [
  {
    id: 31176880,
    number: "491891******5005",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "test test",
    expMonth: 7,
    expYear: 2033,
    addressId: 23168783,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/31176880?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/31176880/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99223778,
    number: "589258******5892",
    expires: "06/2026",
    type: "MasterCard",
    typeID: 6,
    html: '<img src="https://img.shop.com/Image/local/images/cc/mastercard.png" alt="MasterCard" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/mastercard.svg",
    categoryID: 1,
    cvv: 1,
    token: "51c4ade6-f659-11df-b64c-005056842e7d",
    accountName: "test AI-97101",
    mask: "589258******5892",
    expMonth: 6,
    expYear: 2026,
    addressId: 23207864,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99223778?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99223778/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99223779,
    number: "378282*****0005",
    expires: "05/2026",
    type: "American Express",
    typeID: 1,
    html: '<img src="https://img.shop.com/Image/local/images/cc/amex.jpg" alt="American Express Cards" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/amex.svg",
    categoryID: 1,
    cvv: 1,
    token: "32ac68ae-f651-11df-b64c-005056842e7d",
    accountName: "AMEX AI-97101",
    mask: "378282*****0005",
    expMonth: 5,
    expYear: 2026,
    addressId: 23207865,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99223779?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99223779/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99223781,
    number: "491891******5005",
    expires: "04/2037",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "visa save",
    mask: "491891******5005",
    expMonth: 4,
    expYear: 2037,
    addressId: 23207867,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99223781?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99223781/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297419,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492787,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297419?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297419/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297420,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492788,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297420?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297420/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297421,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492789,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297421?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297421/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297435,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492832,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297435?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297435/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297436,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492833,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297436?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297436/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297437,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492834,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297437?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297437/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297438,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492836,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297438?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297438/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297439,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492839,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297439?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297439/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297441,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492840,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297441?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297441/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297442,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492841,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297442?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297442/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297443,
    number: "411111******1111",
    expires: "07/2033",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Am",
    mask: "411111******1111",
    expMonth: 7,
    expYear: 2033,
    addressId: 23492845,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297443?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297443/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297673,
    number: "491891******5005",
    expires: "01/2028",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Test Card AA",
    mask: "491891******5005",
    expMonth: 1,
    expYear: 2028,
    addressId: 23493532,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297673?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297673/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297674,
    number: "491891******5005",
    expires: "01/2028",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "8206a9b9-e8fd-11df-b64c-005056842e7d",
    accountName: "Test Card AA",
    mask: "491891******5005",
    expMonth: 1,
    expYear: 2028,
    addressId: 23493531,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297674?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297674/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297685,
    number: "411111******1111",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Test W121",
    mask: "411111******1111",
    addressId: 23493567,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297685?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297685/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297686,
    number: "411111******1111",
    expires: "02/2031",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Test W121",
    mask: "411111******1111",
    expMonth: 2,
    expYear: 2031,
    addressId: 23493566,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297686?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297686/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297804,
    number: "411111******1111",
    expires: "03/2032",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "test Card",
    mask: "411111******1111",
    expMonth: 3,
    expYear: 2032,
    addressId: 23493982,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297804?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297804/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297808,
    number: "411111******1111",
    expires: "03/2028",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Test Card",
    mask: "411111******1111",
    expMonth: 3,
    expYear: 2028,
    addressId: 23493985,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297808?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297808/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297809,
    number: "411111******1111",
    expires: "03/2028",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Test Card",
    mask: "411111******1111",
    expMonth: 3,
    expYear: 2028,
    addressId: 23493986,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297809?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297809/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297812,
    number: "411111******1111",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Test Card",
    mask: "411111******1111",
    addressId: 23493988,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297812?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297812/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  {
    id: 99297813,
    number: "411111******1111",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Test Card",
    mask: "411111******1111",
    addressId: 23493987,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297813?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99297813/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
  
  {
    id: 99298269,
    number: "411111******1111",
    expires: "04/2035",
    type: "Visa",
    typeID: 9,
    html: '<img src="https://img.shop.com/Image/local/images/cc/visa.jpg" alt="Visa" align="middle">',
    imageUrl: "https://img.shop.com/Image/local/images/cc/visa.svg",
    categoryID: 1,
    cvv: 1,
    token: "970bb564-97df-4d5a-93b4-499153ac3ed6",
    accountName: "Test Card",
    mask: "411111******1111",
    preferred: true,
    expMonth: 4,
    expYear: 2035,
    addressId: 23495306,
    shopperAccountDisabled: 0,
    links: [
      {
        rel: "update",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99298269?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "cvvCheck",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/99298269/cvv?siteId=0",
        type: "application/json; charset=UTF-8",
      },
      {
        rel: "addresses",
        href: "/Shopper/WxxeWXwhzWUhmzhYXVzYzzezkexjewwqhpXkzehwpz/Wallet/Addresses?siteId=0",
        type: "application/json; charset=UTF-8",
      },
    ],
  },
];

export const ADDRESSES_WITH_ID = {
  "23207867": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23207867,
    description: "test, po, monterey",
    isoalpha3Code: "USA",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address1: "123 test po box",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23168783": {
    isPoBox: false,
    stateID: 5,
    hasAddress: 0,
    state: "CA",
    first: "dev",
    last: "test",
    country: "United States",
    region: "",
    id: 23168783,
    description: "test, dev, monterey",
    isoalpha3Code: "USA",
    city: "monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "123 test rd",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23207864": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23207864,
    state: "CA",
    description: "test, po, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1112222333",
    address1: "123 test MC rd",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492787": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492787,
    description: "test, po, monterey",
    isoalpha3Code: "USA",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23207865": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "test",
    last: "test",
    country: "United States",
    region: "",
    id: 23207865,
    state: "CA",
    description: "test, test, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "postal box 764",
    address2: "testing AI-97101",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492788": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492788,
    state: "CA",
    description: "test, po, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492789": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492789,
    description: "test, po, monterey",
    isoalpha3Code: "USA",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492832": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492832,
    description: "test, po, monterey",
    isoalpha3Code: "USA",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492833": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492833,
    state: "CA",
    description: "test, po, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492834": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492834,
    state: "NY",
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492840": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492840,
    state: "NY",
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492836": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492836,
    state: "NY",
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492839": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492839,
    state: "NY",
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492845": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    state: "NY",
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492845,
    description: "w, vikas, New York",
    isoalpha3Code: "USA",
    city: "New York",
    zip: "10001",
    phone: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492841": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492841,
    state: "NY",
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493532": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493532,
    description: "update2, update1, Monterey",
    isoalpha3Code: "USA",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493567": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493567,
    description: "update2, update1, Monterey",
    isoalpha3Code: "USA",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493531": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493531,
    state: "CA",
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493566": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493566,
    state: "CA",
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493982": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493982,
    description: "update2, update1, Monterey",
    isoalpha3Code: "USA",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493987": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493987,
    state: "CA",
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493988": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493988,
    description: "update2, update1, Monterey",
    isoalpha3Code: "USA",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493985": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493985,
    state: "CA",
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493986": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493986,
    description: "update2, update1, Monterey",
    isoalpha3Code: "USA",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
};

export const SHOPPER_WALLET_ADDRESS = {
  "23168783": {
    isPoBox: false,
    stateID: 5,
    hasAddress: 0,
    state: "CA",
    first: "dev",
    last: "test",
    country: "United States",
    region: "",
    id: 23168783,
    description: "test, dev, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "123 test rd",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23207867": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23207867,
    state: "CA",
    description: "test, po, monterey",
    phone: "1888333444",
    city: "monterey",
    zip: "93940",
    address1: "123 test po box",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23207865": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "test",
    last: "test",
    country: "United States",
    region: "",
    id: 23207865,
    state: "CA",
    description: "test, test, monterey",
    phone: "1112223333",
    city: "monterey",
    zip: "93940",
    address1: "postal box 764",
    address2: "testing AI-97101",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492787": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492787,
    description: "test, po, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23207864": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23207864,
    description: "test, po, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1112222333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "123 test MC rd",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23492789": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492789,
    description: "test, po, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23492833": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492833,
    state: "CA",
    description: "test, po, monterey",
    phone: "1888333444",
    city: "monterey",
    zip: "93940",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492832": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492832,
    description: "test, po, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1888333444",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23492834": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492834,
    state: "NY",
    description: "w, vikas, New York",
    phone: "",
    city: "New York",
    zip: "10001",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492788": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "po",
    last: "test",
    country: "United States",
    region: "",
    id: 23492788,
    state: "CA",
    description: "test, po, monterey",
    phone: "1888333444",
    city: "monterey",
    zip: "93940",
    address1: "123 test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492836": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    state: "NY",
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492836,
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23492841": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492841,
    state: "NY",
    description: "w, vikas, New York",
    phone: "",
    city: "New York",
    zip: "10001",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492839": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    state: "NY",
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492839,
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23492845": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492845,
    state: "NY",
    description: "w, vikas, New York",
    phone: "",
    city: "New York",
    zip: "10001",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23492840": {
    isPoBox: false,
    stateID: 37,
    hashCode: "",
    hasAddress: 0,
    state: "NY",
    first: "vikas",
    last: "w",
    country: "United States",
    region: "",
    id: 23492840,
    description: "w, vikas, New York",
    city: "New York",
    zip: "10001",
    phone: "",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "NY",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23493532": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493532,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23493567": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493567,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23493985": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493985,
    state: "CA",
    description: "update2, update1, Monterey",
    phone: "1112223333",
    city: "Monterey",
    zip: "93940",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493986": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493986,
    state: "CA",
    description: "update2, update1, Monterey",
    phone: "1112223333",
    city: "Monterey",
    zip: "93940",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493988": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493988,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23493531": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493531,
    state: "CA",
    description: "update2, update1, Monterey",
    phone: "1112223333",
    city: "Monterey",
    zip: "93940",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493987": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493987,
    state: "CA",
    description: "update2, update1, Monterey",
    phone: "1112223333",
    city: "Monterey",
    zip: "93940",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23493566": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493566,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23493982": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23493982,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23495306": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23495306,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23495835": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23495835,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23495639": {
    isPoBox: false,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "express",
    last: "test",
    country: "United States",
    region: "",
    id: 23495639,
    description: "test, express, monterey",
    city: "monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "562 express add test",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
  "23495836": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23495836,
    state: "CA",
    description: "update2, update1, Monterey",
    phone: "1112223333",
    city: "Monterey",
    zip: "93940",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    mi: "",
  },
  "23495840": {
    isPoBox: true,
    stateID: 5,
    hashCode: "",
    hasAddress: 0,
    state: "CA",
    first: "update1",
    last: "update2",
    country: "United States",
    region: "",
    id: 23495840,
    description: "update2, update1, Monterey",
    city: "Monterey",
    zip: "93940",
    phone: "1112223333",
    address4: "",
    address5: "",
    address6: "",
    address7: "",
    address1: "po box 421212",
    address2: "",
    address3: "",
    company: "",
    isoalpha3Code: "USA",
    mi: "",
  },
};
